### PR TITLE
Fixes for occasionally creating empty files when artifact doesn't exist and for running multiple git commands

### PR DESCRIPTION
**Pull request by pwheel**
Two fixes in one PR, hope that's okay.

1 - Similar (same?) issue as #23 and #25. I thought that the fixes for #25 resolved everything, but when building with a completely clean local repository, I had the same issue as #23. I've compared the source code of StreamWagon to see what it does, and it calls fireGetInitiated() before checking whether the resource exists, and throws a TransferFailedException if it doesn't. I've updated the code to do the same thing. This resolved the issue for me.

2 - I have a couple of jars in my git repo and maven kicked off 2 gets for them at the same time. This meant that the second always failed as .git/index.lock existed in my local git repo due to the command being run by the first get. I've added synchronised to the run()  method to prevent this.

### CODE REVIEW

**Comment by mschonaker** [comment]
Cool stuff. Thank you.

Shouldn't we delete the local file (just like StreamWagon) as well?

About locking/synchronization, the problem could happen anyway if maven somehow starts another process or another process is running. I'd wish to find a way to get git awaiting for its own locks. Maybe command switches.

Anyways, I'll merge ASAP.

Thank you again.

**Comment by pwheel** [comment]
No problem, thanks.

Can you point me to where StreamWagon deletes the local file? I've missed that.

re locking, true - I'd thought to do something like waiting for the index.lock fail to be deleted, but most of the time the problem will happen within the same JVM so that was the simplest thing :)

**Comment by pwheel** [comment]
Hi Martin, I was still having some problem deploying to an empty repository. I've changed GitWagon to extend StreamWagon which takes care of the details and throwing the right errors. The implementation of fillInputData() and fillOutputData() is taken from FileWagon.

This seems to fix my use cases.

**Comment by mschonaker** [comment]
Looks like a very deep change, although in the correct direction :)

I would like to test this around a little bit. In the meantime would you mind to add some logging messages?

**Comment by mschonaker** [comment]
Okay. So I finally got the time to merge and deploy a SNAPSHOT [0.3.0-SNAPSHOT](https://github.com/synergian/wagon-git/tree/snapshots/ar/com/synergian/wagon-git/0.3.0-SNAPSHOT) . 

The artifact deployed itself :)

I would like someone else to give it a try. So with a few of these tests I would release 0.3.0.

**Comment by pwheel** [comment]
Awesome :+1: Sorry, I never got round to adding the logging you asked for but I see you've added it :)

**Comment by mschonaker** [comment]
Did the snapshot work (to anyone)?

**Comment by mschonaker** [comment]
Doesn't work with sites.

**Comment by mschonaker** [comment]
Doesn't look related to this. I'm having this stacktrace: https://issues.apache.org/jira/browse/MRUNIT-209

**Comment by mschonaker** [comment]
Well, after testing with several Maven versions, it doesn't work with sites. Sorry. Reverting.

    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] BUILD FAILURE
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Total time: 51.744s
    [INFO] [INFO] Finished at: Mon May 02 21:27:13 ART 2016
    [INFO] [INFO] Final Memory: 29M/323M
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:deploy (default-deploy) on project wagon-git: Wagon protocol 'git' doesn't support directory copying -> [Help 1]
    [INFO] [ERROR] 
    [INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [INFO] [ERROR] 
    [INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1:14.922s
    [INFO] Finished at: Mon May 02 21:27:14 ART 2016
    [INFO] Final Memory: 12M/309M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.1:perform (default-cli) on project wagon-git: Maven execution failed, exit code: '1' -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by pwheel** [comment]
Ah, I never tested that. Do you have an example pom I could test with by any chance?

**Comment by mschonaker** [comment]
wagon-git deploys to Github itself. I wasn't able to deploy the site part.

**Pull request closed without merging**
